Add support for Debian 12
voxpupuli/puppet-fail2ban pull request #197
Opened 2023-06-23 17:35 UTC by cFire

#### Pull Request (PR) description
Created the template for Debian 12 based on the default jail.conf that ships with the fail2ban bookworm package.

#### This Pull Request (PR) fixes the following issues
n/a

2023-07-17 19:35 UTC, cFire commented
Are Debian 12 tests something I can add in the PR? Or do they need to be configured elsewhere?

2023-07-17 19:42 UTC, kenyon requested changes
Tests for Debian 12 bookworm won't work until packages are available: https://tickets.puppetlabs.com/browse/PA-4995

2023-07-17 19:42 UTC, kenyon commented on templates/Debian/12/etc/fail2ban/jail.conf.epp
> +logpath = /var/log/monitorix-httpd
Add final newline:

```suggestion
logpath = /var/log/monitorix-httpd

```

2023-12-14 20:10 UTC, tskirvin commented
This doesn't work on Debian 12.  The default `fail2ban::action` is still set to `action_mb`, which doesn't exist for Debian 12 in this template. FYI.

2023-12-14 20:34 UTC, cFire commented
> This doesn't work on Debian 12. The default `fail2ban::action` is still set to `action_mb`, which doesn't exist for Debian 12 in this template. FYI.

Thanks for letting me know. I never noticed it was missing since I set a different action in my config. I've merged the actions section from the Debian 11 config into the current file but I don't have a good way to test the `action_mb` on my system, so if you have some way to test and verify that would be great!

2023-12-15 17:55 UTC, tskirvin commented
> > This doesn't work on Debian 12. The default `fail2ban::action` is still set to `action_mb`, which doesn't exist for Debian 12 in this template. FYI.
> 
> Thanks for letting me know. I never noticed it was missing since I set a different action in my config. I've merged the actions section from the Debian 11 config into the current file but I don't have a good way to test the `action_mb` on my system, so if you have some way to test and verify that would be great!

I did a tiny amount of checking, and it works now, but honestly I was convinced to switch back to something besides action_mb anyway because I didn't actually want the emails.  Thanks for the encouragement!

2024-01-18 12:07 UTC, kwisatz commented
This seems to have been approved. Will we see a new release with this included anytime soon?

2024-02-28 16:00 UTC, Valantin approved these changes

2024-04-05 15:36 UTC, merged